name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Starting deployment..."
          cd /var/www/space/cli/
          echo "Current directory: $(pwd)"
          
          # Check Git status
          if [ -d ".git" ]; then
            echo "Git repository exists, updating..."
            git status
            git reset --hard HEAD
            git pull origin main
          else
            echo "Cloning fresh repository..."
            rm -rf * .[^.]*
            git clone https://github.com/isatispooya/space-cli.git .
          fi
          
          # Check Node.js and npm versions
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          
          # Clear npm cache and node_modules
          echo "Cleaning npm cache and node_modules..."
          npm cache clean --force
          rm -rf node_modules package-lock.json
          
          # Install dependencies with verbose logging
          echo "Installing dependencies..."
          npm install --verbose
          
          # Build with verbose logging
          echo "Building project..."
          npm run build
          
          echo "Deployment complete!"