name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        username: ${{secrets.SERVER_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: ${{secrets.SSH_PORT}}
        script: |
          echo "Starting deployment..."
          cd /var/www/space/cli/
          
          if [ -d ".git" ]; then
            echo "Git repository exists, updating..."
            git fetch origin
            git clean -fd
            git reset --hard origin/main
            git pull origin main || { echo "Git pull failed"; exit 1; }
          else
            echo "Cloning repository..."
            rm -rf * .[^.]*
            git clone https://github.com/isatispooya/space-cli.git . || { echo "Git clone failed"; exit 1; }
          fi
          
          echo "Installing dependencies..."
          rm -rf node_modules
          npm install || { echo "npm install failed"; exit 1; }
          
          echo "Building project..."
          npm run build || { echo "Build failed"; exit 1; }
          
          if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
            echo "Error: dist folder or index.html not found"
            exit 1
          fi
          
          echo "Checking dist directory contents:"
          ls -la dist/
          
          echo "Restarting PM2 service..."
          pm2 delete space-client || echo "No existing PM2 process found"
          NODE_NO_WARNINGS=1 pm2 start http-server --name space-client -- /var/www/space/cli/dist -p 2084 --cors || { echo "PM2 start failed"; exit 1; }
          pm2 save || { echo "PM2 save failed"; exit 1; }
          
          echo "Deployment completed successfully"