name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        username: ${{secrets.SERVER_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: ${{secrets.SSH_PORT}}
        script: |
          cd /var/www/space/cli/
          if [ -d ".git" ]; then
            git fetch origin
            git clean -fd
            git reset --hard origin/main
            git pull origin main
          else
            rm -rf * .[^.]*
            git clone https://github.com/isatispooya/space-cli.git .
          fi
          
          rm -rf node_modules
          npm install
          npm run build || exit 1
          
          if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
            echo "Error: dist folder or index.html not found"
            exit 1
          fi
          
          ls -la dist/
          pm2 delete space-client || true
          NODE_NO_WARNINGS=1 pm2 start http-server --name space-client -- /var/www/space/cli/dist -p 2084 --cors
          pm2 save