name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: "31.40.4.92"
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2233
        script: |
          cd /var/www/space/cli/
          if [ -d ".git" ]; then
            git reset --hard HEAD
            git pull origin main
          else
            rm -rf * .[^.]*
            git clone https://github.com/isatispooya/space-cli.git .
          fi
          npm install
          npm run build